// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4909.STEAMWORKS.subsystems;

import org.usfirst.frc4909.STEAMWORKS.Robot;
import org.usfirst.frc4909.STEAMWORKS.RobotMap;
import org.usfirst.frc4909.STEAMWORKS.PID.PIDController;
import org.usfirst.frc4909.STEAMWORKS.commands.*;

import com.kauailabs.navx.frc.AHRS;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */

public class Drivetrain extends Subsystem {

    private double rotateP = 0.1;
	private double rotateI = 0.00000;
	private double rotateD = 0.00000;


    private double navP = 0.0002;
	private double navI = 0.00000;
	private double navD = 0.00000;
	
	private double encP = 0.005;
	private double encI = 0.00000;
	private double encD = 0.00000;

	//in inches
	private double wheelDiameter = 4.0;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController leftFrontDriveMotorController = RobotMap.drivetrainLeftFrontDriveMotorController;
    private final SpeedController leftBackDriveMotorController = RobotMap.drivetrainLeftBackDriveMotorController;
    private final SpeedController rightBackDriveMotorController = RobotMap.drivetrainRightBackDriveMotorController;
    private final SpeedController rightFrontDriveMotorController = RobotMap.drivetrainRightFrontDriveMotorController;
    private final RobotDrive robotDrive = RobotMap.drivetrainRobotDrive;
    private final Encoder leftEncoder = RobotMap.drivetrainLeftEncoder;
    private final Encoder rightEncoder = RobotMap.drivetrainRightEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    

    private final PIDController rotatePID = new PIDController(rotateP, rotateI, rotateD,.5);
    private final PIDController navxPID = new PIDController(navP, navI, navD,.6);
    private final PIDController encPID = new PIDController(encP, encI, encD,.6);

    
    private final AHRS navx = RobotMap.navx;
    


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
    
    public void moveTank(){
    	double leftY = Robot.oi.getLeftDriveY();
    	double rightY = Robot.oi.getRightDriveY();
    	robotDrive.tankDrive(leftY, rightY);
    	
    	// RETURN SPEED
    	
    }
    
    
    public void rotateAngle(double angle){
    	rotatePID.resetPID();
    	SmartDashboard.putBoolean("rotate", true);
    	double targetTime=Timer.getFPGATimestamp();
    	while(Timer.getFPGATimestamp()-targetTime<.5){
    		rotatePID.atTarget=false;
        	rotateP=SmartDashboard.getNumber("rP", 0);
        	rotateI=SmartDashboard.getNumber("rI", 0);
        	rotateD=SmartDashboard.getNumber("rD", 0);
        	rotatePID.changePIDGains(rotateP, rotateI, rotateD);

    		double currentAngle=getYaw();
    		if(Math.abs(angle-currentAngle)>180){
    			angle = angle + (currentAngle / Math.abs(currentAngle))*360;
    		}
    		SmartDashboard.putNumber("current angle",currentAngle);
    		SmartDashboard.putNumber("PID out",rotatePID.calcPID(angle, currentAngle, 4));

    		robotDrive.arcadeDrive(0,rotatePID.calcPID(angle, currentAngle, 4));
    		if(!rotatePID.isDone()){
    				targetTime=Timer.getFPGATimestamp();
    				
    		}
    	}
    	
    	SmartDashboard.putBoolean("rotate", false);

    }
    //Distance in feet
    public void driveStraightNavX(double dist){
    	navxPID.resetPID();
    	navx.resetDisplacement();
    	SmartDashboard.putNumber("nP", navP);
    	SmartDashboard.putNumber("nI", navI);
    	SmartDashboard.putNumber("nD", navD);

    	double targetTime=Timer.getFPGATimestamp();
    	while(Timer.getFPGATimestamp()-targetTime<.5){
    		navxPID.atTarget=false;
        	navP=SmartDashboard.getNumber("nP", 0);
        	navI=SmartDashboard.getNumber("nI", 0);
        	navD=SmartDashboard.getNumber("nD", 0);
        	navxPID.changePIDGains(navP, navI, navD);

    		double currentDist=getDisplacementY();
    		SmartDashboard.putNumber("current dist",currentDist);
    		SmartDashboard.putNumber("nPID out",navxPID.calcPID(dist, currentDist, .05));

    		robotDrive.arcadeDrive(-navxPID.calcPID(dist, currentDist, .05),0);
    		if(!navxPID.isDone()){
    				targetTime=Timer.getFPGATimestamp();
    				
    		}
    	}
    	
    	SmartDashboard.putBoolean("straight", false);
    }
//Distance in feet
    public void driveStraightEncoder(double dist){
    	navxPID.resetPID();
    	navx.resetDisplacement();
    	SmartDashboard.putNumber("nP", navP);
    	SmartDashboard.putNumber("nI", navI);
    	SmartDashboard.putNumber("nD", navD);

    	double targetTime=Timer.getFPGATimestamp();
    	while(Timer.getFPGATimestamp()-targetTime<.5){
    		navxPID.atTarget=false;
        	navP=SmartDashboard.getNumber("nP", 0);
        	navI=SmartDashboard.getNumber("nI", 0);
        	navD=SmartDashboard.getNumber("nD", 0);
        	navxPID.changePIDGains(navP, navI, navD);

    		double currentDist=getDisplacementY();
    		SmartDashboard.putNumber("current dist",currentDist);
    		SmartDashboard.putNumber("nPID out",navxPID.calcPID(dist, currentDist, .05));

    		robotDrive.arcadeDrive(-navxPID.calcPID(dist, currentDist, .05),0);
    		if(!navxPID.isDone()){
    				targetTime=Timer.getFPGATimestamp();
    				
    		}
    	}
    	
    	SmartDashboard.putBoolean("straight", false);
    }
    
    public double getYaw(){
    	return navx.getYaw();
    }
    public double getDisplacementX(){
    	return navx.getDisplacementX();
    }
    public double getDisplacementY(){
    	return navx.getDisplacementY();
    }
    public double getDisplacementZ(){
    	return navx.getDisplacementZ();
    }
    
    public void stop(){
    	robotDrive.drive(0, 0);
    }
}
